# Generated by Django 5.0.4 on 2024-07-06 15:31

import autoslug.fields
import blog.models
import ckeditor_uploader.fields
import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary_text', models.CharField(max_length=168)),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=8000, null=True)),
                ('comments_enable', models.BooleanField(default=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=blog.models.imageUpload, variations={'large': (600, 400), 'medium': (300, 200), 'thumbnail': (80, 80, True)})),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.categorymodel')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='blog_posts', to='blog.tagmodel')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('comment', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', editable=False, primary_key=True, serialize=False, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
