# Generated by Django 5.0.4 on 2024-07-07 17:47

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
